version: "3.8"

networks:
  kong-network:
    driver: bridge

services:
  rabbitmq:
    container_name: rabbit-booking
    image: rabbitmq:3.12
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1234
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - kong-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  redis:
    image: redis:6
    container_name: redis
    networks:
      - kong-network
    ports:
      - "6379:6379"

  kong:
    image: kong:3.6
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8080
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml
    ports:
      - "8080:8080"
      - "8001:8001"
    networks:
      - kong-network
    depends_on:
      - user-service

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./data/data_db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: user_service
    ports:
      - '5432:5432'
    networks:
      - kong-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d user_service']
      interval: 10s
      retries: 5
      start_period: 10s

  user-service:
    container_name: user-service
    build: ./user-service-v2
    image: lehau17/user-service:latest
    ports:
      - '5000:5000'
    networks:
      - kong-network
    environment:
      DATABASE_URL: 'postgresql://admin:admin1234@postgres:5432/user_service?schema=public'
      JWT_ACCESS_TOKEN_SECRET: 'sndkjbvfskdvfhjsvdfjhvsdjfhvsdkjfhvsjdhfvskdhvfkjshvdfhjk'
      JWT_REFRESH_TOKEN_SECRET: 'jwt_refresh_token'
      JWT_ACCESS_TOKEN_EXPIRES: '15m'
      JWT_REFRESH_TOKEN_EXPIRES: '7d'
      LIMIT_GLOBAL: '10'
      PORT: '5000'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      RATE_LIMIT_PUBLIC: 3
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  room-service:
    container_name: room-service
    build: ./room-service
    image: lehau17/room-service:latest
    ports:
      - '5001:5001'
    networks:
      - kong-network
    environment:
      MONGO_URI: 'mongodb://mongo:27017/room-service'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      RATE_LIMIT_PUBLIC: 3
      USER_SERVICE_URL: http://user-service:5000
    depends_on:
      - mongo
      - redis


  payment-service:
    container_name: payment-service
    build: ./payment-service
    image: lehau17/payment-service:latest
    ports:
      - '5959:5959'
    networks:
      - kong-network
    environment:
      PORT: 5959
      MONGO_URI: mongodb://mongo:27017/paymentService
      RABBITMQ_URL: amqp://admin:1234@rabbitmq:5672
      QUEUE_NAME: confirm.queue
      RABBITMQ_EXCHANGE: booking.exchange
      REDIS_URL: redis://redis:6379

    depends_on:
      - mongo
      - redis
      - rabbitmq


  notify-service:
    container_name: notify-service
    build: ./notify-service
    image: lehau17/notify-service:latest
    ports:
      - '5005:5005'
    networks:
      - kong-network
    environment:
      MONGO_URI: 'mongodb://mongo:27017/room-service'
      PORT: 5005
      RABBITMQ_URL: amqp://admin:1234@rabbitmq:5672
      RABBITMQ_QUEUE: booking_queue
    depends_on:
      - mongo
      - redis

  upload-service:
    container_name: upload-service
    build: ./upload-service
    image: lehau17/upload-service:latest
    ports:
      - '9999:9999'
    networks:
      - kong-network
    depends_on:
      - mongo
      - minio
      - redis


  invoice-service:
    container_name: invoice-service
    build: ./invoice-service
    image: lehau17/invoice-service:latest
    ports:
      - '5004:5004'
    networks:
      - kong-network
    environment:
      PORT: 5004
      MONGO_URI: mongodb://mongo:27017/invoiceService
      RABBITMQ_URL: amqp://admin:1234@rabbitmq:5672
      RABBITMQ_QUEUE: booking_queue
      REDIS_URL: redis://redis:6379
      QUEUE_NAME: confirm.queue
      RABBITMQ_EXCHANGE: booking.exchange
      RABBITMQ_DEFAULT_VHOST: /

    depends_on:
      - rabbitmq
      - mongo
      - redis
  mongo:
    image: mongo:6
    networks:
      - kong-network
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./data/minio:/data
      - ./config/minio:/root/.minio
    command: server /data --console-address ":9001"
    networks:
      - kong-network

  booking-service:
    container_name: booking-service
    build: ./BookingService
    image: lehau17/booking-service:latest
    ports:
      - '8085:8080'
    networks:
      - kong-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/booking-service
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: 1234
      SERVER_PORT: 8080
    depends_on:
      - mongo
      - rabbitmq
      - redis

    # Node Exporter để thu thập metrics máy chủ
  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   restart: always
  #   ports:
  #     - "9100:9100"
  #   networks:
  #     - kong-network

  # # Prometheus để scrape metrics
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   restart: always
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - kong-network
  #   depends_on:
  #     - node-exporter
  #     - mongo
  #     - postgres

  # # Grafana để visualize metrics
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - kong-network
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus

  # postgres-exporter:
  #   image: prometheuscommunity/postgres-exporter
  #   container_name: postgres-exporter
  #   restart: always
  #   ports:
  #     - "9187:9187"
  #   networks:
  #     - kong-network
  #   environment:
  #     DATA_SOURCE_NAME: "postgresql://admin:admin1234@postgres:5432/user_service?sslmode=disable"
  #   depends_on:
  #     - postgres


  # mongo-exporter:
  #   image: bitnami/mongodb-exporter:latest
  #   container_name: mongo-exporter
  #   restart: always
  #   ports:
  #     - "9216:9216"
  #   networks:
  #     - kong-network
  #   environment:
  #     - MONGODB_URI=mongodb://mongo:27017
  #   depends_on:
  #     - mongo



  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - ELASTIC_PASSWORD=changeme
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   networks:
  #     - elk

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.15.0
  #   container_name: logstash
  #   environment:
  #     - LS_JAVA_OPTS="-Xmx256m -Xms256m"
  #   ports:
  #     - "5044:5044"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch
  #   volumes:
  #     - ./elk_stask/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./elk_stask/logstash/driver:/usr/share/logstash/driver

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.6.0
  #   container_name: kibana
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - ELASTICSEARCH_PASSWORD=changeme
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch
  # nginx:
  #   image: "jc21/nginx-proxy-manager:latest"
  #   restart: unless-stopped
  #   ports:
  #     # These ports are in format <host-port>:<container-port>
  #     - 80:80 # Public HTTP Port
  #     - 443:443 # Public HTTPS Port
  #     - 81:81 # Admin Web Port
  #     # Add any other Stream port you want to expose
  #     # - '21:21' # FTP
  #   networks:
  #     - node-network
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt
